export const keywords = [
  "zobaidul kazi",
  "zobaidul",
  "kazi",
  "kazi-byte",
  "zobaidul kazi blog",
  "zobaidul kazi blog about react",
  "zobaidul kazi website",
  "zobaidul kazi developer",
  "zobaidul kazi programmer",
  "zobaidul kazi portfolio",
  "zobaidul kazi projects",
  "zobaidul kazi GitHub",
  "zobaidul kazi LinkedIn",
  "zobaidul kazi Twitter",
  "zobaidul kazi social media",
  "zobaidul kazi articles",
  "zobaidul kazi tutorials",
  "zobaidul kazi courses",
  "zobaidul kazi JavaScript",
  "zobaidul kazi React",
  "zobaidul kazi Next.js",
  "zobaidul kazi TypeScript",
  "zobaidul kazi web development",
  "zobaidul kazi software development",
  "zobaidul kazi coding",
  "zobaidul kazi programming",
  "zobaidul kazi tech",
  "zobaidul kazi computer science",
  "zobaidul kazi technology",
  "zobaidul kazi innovation",
  "zobaidul kazi inspiration",
  "zobaidul kazi motivation",
  "zobaidul kazi creativity",
  "zobaidul kazi design",
  "zobaidul kazi UI/UX",
  "zobaidul kazi front end",
  "zobaidul kazi back end",
  "zobaidul kazi full stack",
  "zobaidul kazi developer tools",
  "zobaidul kazi frameworks",
  "zobaidul kazi libraries",
  "zobaidul kazi coding tips",
  "zobaidul kazi programming tricks",
  "zobaidul kazi software engineering",
  "zobaidul kazi web technologies",
  "zobaidul kazi blog posts",
  "zobaidul kazi articles",
  "zobaidul kazi tutorials",
  "zobaidul kazi videos",
  "zobaidul kazi podcasts",
  "zobaidul kazi interviews",
  "zobaidul kazi resources",
  "zobaidul kazi learning",
  "zobaidul kazi education",
  "zobaidul kazi knowledge",
  "zobaidul kazi skills",
  "zobaidul kazi experience",
  "zobaidul kazi expertise",
  "zobaidul kazi passion",
  "zobaidul kazi dedication",
  "zobaidul kazi commitment",
  "zobaidul kazi success",
  "zobaidul kazi achievements",
  "zobaidul kazi goals",
  "zobaidul kazi aspirations",
  "zobaidul kazi dreams",
  "zobaidul kazi future",
  "zobaidul kazi career",
  "zobaidul kazi professional",
  "zobaidul kazi personal",
  "zobaidul kazi journey",
  "zobaidul kazi mission",
  "zobaidul kazi vision",
  "zobaidul kazi values",
  "zobaidul kazi principles",
  "zobaidul kazi ethics",
  "zobaidul kazi impact",
  "zobaidul kazi influence",
  "zobaidul kazi community",
  "zobaidul kazi world",
  "zobaidul kazi global",
  "zobaidul kazi local",
  "zobaidul kazi society",
  "zobaidul kazi culture",
  "zobaidul kazi diversity",
  "zobaidul kazi inclusion",
  "zobaidul kazi equity",
  "zobaidul kazi justice",
  "zobaidul kazi equality",
];
